name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x] # test 2 versions of node for a diffoscope later

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  path: "WellQuest"
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: "./package-lock.json"
            - run: |
                  npm install 
                  npm run build --if-present # build the package
            - name: Run Jest tests
              run: |
                  npm test # run the tests
